#base "../#bases/reload_scheme.res"
#base "base/classloadoutpanel.res"
//#base "../#jofre/multiple-bg.res"
#base "base/filesv2/loadout_preset_panel/main.res"
#base "base/filesv2/loadout_preset_panel/main2.res"
#base "base/filesv2/topline/main.res"
#base "base/filesv2/topline/content1.res"
#base "base/filesv1/itemrename/mouseoveritem.res"