#base "res_base/classselection.res"
#base "base/filesv3-hint/cancel/main.res"
#base "base/filesv3-hint/cancel/is_csc.res"
#base "base/filesv3-hint/cancel/wd25.res"
#base "base/filesv3-hint/cancel/vis1.res"
#base "base/filesv3-hint/cancel/pin2.res"
#base "base/filesv3-hint/prev-next/next-main.res"
#base "base/filesv3-hint/prev-next/next-wt25.res"