#base "base/filesv1/desclabel/main.res"
#base "base/filesv1/desclabel/content1.res"
#base "base/filesv1/desclabel/ext/vis1.res"
#base "base/filesv1/desclabel/ext/enabled1.res"
#base "base/filesv1/desclabel/ext/auto1.res"
#base "base/filesv1/desclabel/ext/pin0.res"