#base "../../#uni_base/filesv2/confirmdialog/main.res"
#base "../../#uni_base/filesv2/confirmdialog/x_pos/cen_-150.res"
#base "../../#uni_base/filesv2/confirmdialog/y_pos/_140.res"
#base "../../#uni_base/filesv2/confirmdialog/wide_/_300.res"
#base "../../#uni_base/filesv2/confirmdialog/tall_/_250.res"