#base "base/filesv1/centerpositioner/main.res"
#base "base/filesv1/recipeitemmodelpanel/main.res"
#base "base/filesv1/ellipseslabel/main.res"
#base "base/filesv1/craftingstatusdialog/main.res"


#base "../../#uni_base/filesv1/closebutton/main.res"
#base "../../#uni_base/filesv1/closebutton/vis1.res"
#base "../../#uni_base/filesv1/closebutton/text/center.res"
#base "../../#uni_base/filesv1/closebutton/enabled.res"
#base "../../#uni_base/filesv1/closebutton/ctrl/ceximage.res"
#base "../../#uni_base/filesv1/closebutton/position/wide100.res"
#base "../../#uni_base/filesv1/closebutton/position/tall25.res"
#base "../../#uni_base/filesv1/closebutton/auto.res"
#base "../../#uni_base/filesv1/closebutton/pin3.res"
#base "../../#uni_base/filesv1/closebutton/dull0.res"
#base "../../#uni_base/filesv1/closebutton/bright0.res"
#base "../../#uni_base/filesv1/closebutton/def1.res"
#base "../../#uni_base/filesv1/closebutton/zpos1.res"
#base "../../#uni_base/filesv1/closebutton/sound.res"

#base "../../#uni_base/filesv1/closebutton/label/gameui_ok.res"
#base "../../#uni_base/filesv1/closebutton/cmd/close.res"