#base "res_base/hudarenateammenu.res"
#base "base/filesv3-hint/cancel/main.res"
#base "base/filesv3-hint/cancel/is_csc.res"
#base "base/filesv3-hint/cancel/wd25.res"
#base "base/filesv3-hint/cancel/vis0.res"
#base "base/filesv3-hint/cancel/pin2.res"