//#base "../#bases/1rankpanel.res"
	#base "base/filesv1/rankpanel/main.res"
	#base "base/filesv1/rankpanel/cminipvp.res"
	#base "base/filesv1/rankpanel/x_cs-0.5.res"	
	#base "base/filesv1/rankpanel/full.res"
	#base "base/filesv1/rankpanel/show.res"
	#base "base/filesv1/rankpanel/matchgroup_6.res"
	#base "base/filesv1/drawingpanel/main.res"