#base "../../#uni_base/filesv1/name/global.res"
#base "../../#uni_base/filesv1/name/main1.res"
#base "../../friends/base/namelabel_main.res"
#base "../../friends/base/namelabel_main2.res"
#base "../../friends/base/namelabel_autoresize0.res"
#base "../../friends/base/namelabel_pincorner.res"
#base "../../#uni_base/filesv3/namelabel/tall20.res"
#base "base/filesv2/classmodelpanel/content_import.res"