#base "../../#uni_base/filesv1/background/bg_main.res"
#base "../../#uni_base/filesv1/background/bg_vis1.res"
#base "../../#uni_base/filesv1/background/position/y_0.res"
#base "../../#uni_base/filesv1/background/position/x_0.res"
#base "../../#uni_base/filesv1/background/position/wide_f0.res"
#base "../../#uni_base/filesv1/background/controlname/editable.res"