#base "../../#uni_base/filesv2/confirmdialog/main.res"
#base "../../#uni_base/filesv2/confirmdialog/y_pos/_140.res"
#base "../../#uni_base/filesv2/confirmdialog/wide_/_300.res"
#base "../../#uni_base/filesv2/confirmdialog/tall_/_240.res"

#base "base/filesv2/explanationlabel/main.res"
#base "base/filesv2/explanationlabel/font/hudfontsmallbold.res"
#base "base/filesv2/explanationlabel/label/%text.res"
#base "base/filesv2/explanationlabel/text/north.res"
#base "base/filesv2/explanationlabel/text/centerwrap.res"
#base "base/filesv2/explanationlabel/vis1.res"
#base "base/filesv2/explanationlabel/auto0.res"
#base "base/filesv2/explanationlabel/pin0.res"
#base "base/filesv2/explanationlabel/position/xpos40.res"
#base "base/filesv2/explanationlabel/position/ypos50.res"
#base "base/filesv2/explanationlabel/position/wide220.res"
#base "base/filesv2/explanationlabel/position/tall170.res"
#base "base/filesv2/explanationlabel/fgcolor_1.res"