#base "../../#uni_base/filesv2/confirmdialog/main.res"
#base "base/filesv1/msglabel/main.res"

#base "../../#uni_base/filesv1/titlelabel/controlname/cex.res"
#base "../../#uni_base/filesv1/titlelabel/main.res"
#base "../../#uni_base/filesv1/titlelabel/text/north.res"
#base "../../#uni_base/filesv1/titlelabel/text/centerwrap.res"
#base "../../#uni_base/filesv1/titlelabel/auto.res"
#base "../../#uni_base/filesv1/titlelabel/pin.res"
#base "../../#uni_base/filesv1/titlelabel/vis1.res"
#base "../../#uni_base/filesv1/titlelabel/enabled.res"