#base "../#uni_base/filesv1/timeremaininglabel/main.res"
#base "../#uni_base/filesv1/timeremaininglabel/vis1.res"
#base "../#uni_base/filesv1/timeremaininglabel/dull0.res"
#base "../#uni_base/filesv1/timeremaininglabel/xpos20.res"

#base "../#uni_base/filesv1/cancelbutton/cancelbutton_is-button.res"
#base "../#uni_base/filesv1/cancelbutton/cancelbutton_autoresize_pin.res"
#base "../#uni_base/filesv1/cancelbutton/cancelbutton_def0.res"
#base "../#uni_base/filesv1/cancelbutton/cancelbutton_vis1.res"

#base "../#uni_base/filesv1/cancelbutton/cancelbutton_west.res"
#base "../#uni_base/filesv1/cancelbutton/extra/tab0.res"
#base "../#uni_base/filesv1/cancelbutton/extra/dull0.res"
#base "../#uni_base/filesv1/cancelbutton/extra/bright0.res"
#base "../#uni_base/filesv1/cancelbutton/extra/wrap0.res"