#base "../#uni_base/filesv1/deletebutton/commandisdelete.res"
#base "../#uni_base/filesv1/deletebutton/main.res"
#base "../#uni_base/filesv1/deletebutton/isbtn.res"
#base "../#uni_base/filesv1/deletebutton/content2.res"
#base "base/filesv1/gotobutton/main.res"
#base "base/filesv1/entities/main.res"