#base "../#uni_base/filesv1/loadinglabel/ctrl/frame.res"
#base "../#uni_base/filesv1/loadinglabel/main.res"
#base "../#uni_base/filesv1/loadinglabel/position/x322.res"
#base "../#uni_base/filesv1/loadinglabel/position/y249.res"
#base "../#uni_base/filesv1/loadinglabel/position/w400.res"
#base "../#uni_base/filesv1/loadinglabel/position/t180.res"

#base "../#uni_base/filesv1/cancelbutton/cancelbutton_autoresize_pin.res"
#base "../#uni_base/filesv1/cancelbutton/cancelbutton_is-button.res"
#base "../#uni_base/filesv1/cancelbutton/cancelbutton_def0.res"
#base "../#uni_base/filesv1/cancelbutton/cancelbutton_main.res"
#base "../#uni_base/filesv1/cancelbutton/cancelbutton_vis1.res"
#base "../#uni_base/filesv1/cancelbutton/cancelbutton_west.res"
#base "../#uni_base/filesv1/cancelbutton/label/gameui_cancel.res"
#base "../#uni_base/filesv1/cancelbutton/extra/bright0.res"
#base "../#uni_base/filesv1/cancelbutton/cmd/cancel.res"
#base "../#uni_base/filesv1/cancelbutton/extra/dull0.res"
#base "../#uni_base/filesv1/cancelbutton/extra/tab0.res"
#base "../#uni_base/filesv1/cancelbutton/position/x300.res"
#base "../#uni_base/filesv1/cancelbutton/position/y136.res"
#base "../#uni_base/filesv1/cancelbutton/enabled.res"
#base "../#uni_base/filesv1/cancelbutton/position/w72.res"
#base "../#uni_base/filesv1/cancelbutton/position/t24.res"

#base "../#uni_base/filesv1/vac/main.res"