#base "#bases/buildmodedialog_base.res"
#base "../#uni_base/filesv1/divider1/divider1_main.res"
#base "../#uni_base/filesv1/label1/label1_main.res"
#base "../#uni_base/filesv1/label1/label1_west.res"
#base "base/filesv1/hudquickinfo/main.res"