#base "../#uni_base/filesv1/button2/main.res"
#base "../#uni_base/filesv1/button2/wide_80.res"
#base "../#uni_base/filesv1/button2/tab/is-1.res"
#base "../#uni_base/filesv1/button2/label/gameui-close.res"
#base "../#uni_base/filesv1/button2/def/is-1.res"
#base "../#uni_base/filesv1/button2/def/command-close.res"

#base "../#uni_base/filesv1/label2/main.res"
#base "../#uni_base/filesv1/label2/auto.res"
#base "../#uni_base/filesv1/label2/position/tall20.res"
#base "../#uni_base/filesv1/label2/pin.res"
#base "../#uni_base/filesv1/label2/tab.res"
#base "../#uni_base/filesv1/label2/vis1.res"
#base "../#uni_base/filesv1/label2/enabled.res"
#base "../#uni_base/filesv1/label2/bright0.res"
#base "../#uni_base/filesv1/label2/dull1.res"
#base "../#uni_base/filesv1/label2/wrap0.res"
#base "../#uni_base/filesv1/label2/text/north-west.res"