#base "#bases/buildmodedialog_base.res"
#base "../#uni_base/filesv1/grip_/frames/main.res"
#base "../#uni_base/filesv1/divider1/divider1_main.res"
#base "../#uni_base/filesv1/divider1/divider1_auto-pin0.res"

#base "../#uni_base/filesv1/label1/main.res"
#base "../#uni_base/filesv1/label1/position/tall24.res"
#base "../#uni_base/filesv1/label1/auto.res"
#base "../#uni_base/filesv1/label1/pin.res"
#base "../#uni_base/filesv1/label1/enabled.res"
#base "../#uni_base/filesv1/label1/tab.res"
#base "../#uni_base/filesv1/label1/dull0.res"
#base "../#uni_base/filesv1/label1/bright0.res"
#base "../#uni_base/filesv1/label1/wrap0.res"
#base "../#uni_base/filesv1/label1/text/east.res"

#base "../#uni_base/filesv1/button2/main.res"
#base "../#uni_base/filesv1/button2/wide_80.res"
#base "../#uni_base/filesv1/button2/tab/is-17.res"
#base "../#uni_base/filesv1/button2/label/gameui-cancel.res"
#base "../#uni_base/filesv1/button2/def/is-0.res"
#base "../#uni_base/filesv1/button2/def/command-close.res"
#base "../#uni_base/filesv1/divider2/main.res"
#base "../#uni_base/filesv1/divider2/tallis2.res"
#base "../#uni_base/filesv1/fovslider/main.res

#base "../#uni_base/filesv2/button1/main.res"

#base "../#uni_base/filesv2/button1/position/wide80.res"
#base "../#uni_base/filesv2/button1/position/tall24.res"
#base "../#uni_base/filesv2/button1/extra/auto0.res"
#base "../#uni_base/filesv2/button1/extra/pin0.res"
#base "../#uni_base/filesv2/button1/vis1.res"
#base "../#uni_base/filesv2/button1/enabled.res"
#base "../#uni_base/filesv2/button1/direccion/west.res"
#base "../#uni_base/filesv2/button1/extra/sel0.res"
#base "../#uni_base/filesv2/button1/extra/wrap0.res"
#base "../#uni_base/filesv2/button1/extra/dull0.res"
#base "../#uni_base/filesv2/button1/extra/bright0.res"
#base "../#uni_base/filesv2/button1/extra/cmd/close.res"
#base "../#uni_base/filesv2/button1/extra/def1.res"
#base "../#uni_base/filesv2/button1/label/gameui_ok.res"


#base "../#uni_base/filesv1/label2/main.res"
#base "../#uni_base/filesv1/label2/auto.res"
#base "../#uni_base/filesv1/label2/position/tall24.res"
#base "../#uni_base/filesv1/label2/pin.res"
#base "../#uni_base/filesv1/label2/tab.res"
#base "../#uni_base/filesv1/label2/enabled.res"
#base "../#uni_base/filesv1/label2/bright0.res"
#base "../#uni_base/filesv1/label2/dull0.res"
#base "../#uni_base/filesv1/label2/wrap0.res"
#base "../#uni_base/filesv1/label2/text/east.res"

#base "../#uni_base/filesv1/label3/main.res"
#base "../#uni_base/filesv1/label3/auto.res"
#base "../#uni_base/filesv1/label3/position/tall24.res"
#base "../#uni_base/filesv1/label3/tab.res"
#base "../#uni_base/filesv1/label3/vis1.res"
#base "../#uni_base/filesv1/label3/enabled.res"
#base "../#uni_base/filesv1/label3/bright0.res"
#base "../#uni_base/filesv1/label3/dull0.res"
#base "../#uni_base/filesv1/label3/wrap0.res"
#base "../#uni_base/filesv1/label3/text/west.res"