#base "base/sfm1.res"

#base "../#uni_base/filesv1/label2/main.res"
#base "../#uni_base/filesv1/label2/auto.res"
#base "../#uni_base/filesv1/label2/position/wide64.res"
#base "../#uni_base/filesv1/label2/position/tall24.res"
#base "../#uni_base/filesv1/label2/pin.res"
#base "../#uni_base/filesv1/label2/tab.res"
#base "../#uni_base/filesv1/label2/vis1.res"
#base "../#uni_base/filesv1/label2/enabled.res"
#base "../#uni_base/filesv1/label2/bright0.res"
#base "../#uni_base/filesv1/label2/dull0.res"
#base "../#uni_base/filesv1/label2/wrap0.res"
#base "../#uni_base/filesv1/label2/text/east.res"


#base "../#uni_base/filesv1/okbutton/ctrl/btn.res"
#base "../#uni_base/filesv1/okbutton/main.res"
#base "../#uni_base/filesv1/okbutton/position/wide64.res"
#base "../#uni_base/filesv1/okbutton/position/tall24.res"
#base "../#uni_base/filesv1/okbutton/auto.res"
#base "../#uni_base/filesv1/okbutton/vis1.res"
#base "../#uni_base/filesv1/okbutton/enabled.res"
#base "../#uni_base/filesv1/okbutton/label/vgui_ok.res"
#base "../#uni_base/filesv1/okbutton/cmd/ok.res"
#base "../#uni_base/filesv1/okbutton/text/west.res"
#base "../#uni_base/filesv1/okbutton/wrap0.res"
#base "../#uni_base/filesv1/okbutton/dull0.res"
#base "../#uni_base/filesv1/okbutton/bright0.res"
#base "../#uni_base/filesv1/okbutton/def1res"
#base "../#uni_base/filesv1/okbutton/sel0.res"