	#base 	"../../../_jofrehud/resource/#beta/menu_reloadbutton.res"
	#base	"../../../_jofrehud/resource/#beta/char_classlabel.res"
	#base	"../../../#users/custom/resource/ui/econ/backpackpanel.res"
	#base	"../../../_stream/resource/ui/econ/backpackpanel.res"
	#base	"../../../_jofrehud/resource/ui/econ/backpackpanel.res"
	#base	"../../../_tf2hud/resource/ui/econ/backpackpanel.res"