#base "base/titleinput.res"
#base "../../../#uni_base/filesv1/titlelabel/controlname/cex.res"
#base "../../../#uni_base/filesv1/titlelabel/main.res"
#base "../../../#uni_base/filesv1/titlelabel/auto1.res"
#base "../../../#uni_base/filesv1/titlelabel/pin.res"
#base "../../../#uni_base/filesv1/titlelabel/vis1.res"
#base "../../../#uni_base/filesv1/titlelabel/enabled.res"
#base "../../../#uni_base/filesv1/titlelabel/text/west.res"