#base "../../../#uni_base/filesv1/warninglabel/main.res"
#base "../../../#uni_base/filesv1/warninglabel/west.res"
#base "../../../#uni_base/filesv1/warninglabel/auto0.res"
#base "../../../#uni_base/filesv1/warninglabel/pin0.res"
#base "../../../#uni_base/filesv1/warninglabel/vis0.res"