#base "../base/filesv1/zoombutton/main.res"
#base "../base/filesv1/zoombutton/content2.res"
#base "../base/filesv1/paintnamelabel/main.res"
#base "../base/filesv1/paintnamelabel/content2.res"
#base "../res_base/storepreviewitempanel.res"