#base "../../../../#bases/reload_scheme.res"
#base "../../../base/filesv1/notifipresentpanel/main.res"
#base "../../../base/filesv1/notifipresentpanel/content1.res"
#base "../../../base/filesv1/armory_panel/main.res"
#base "../../../base/filesv2/footerline/main.res"
#base "../../../base/filesv2/bgfooter/main.res"
#base "../../../base/filesv2/bgheader/main.res"
#base "../../../base/filesv2/bgheader/tall_120.res"