#base "../resource/#bases/1sysmenu.res"
#base "base/okutton.res"
#base "base/cancelbutton_main.res"
#base "base/cancelbutton_main2.res"
#base "base/cancelbutton_textalign_west.res"
#base "base/cancelbutton_wideis64.res"
#base "base/cancelbutton_command_cancel.res"