#base "../build_menu/base/hudmenuengybuild.res"
#base "../base/filesv3-hint/build.res"
#base "../base/filesv3-hint/buttonlegend.res"
#base "../base/filesv3-hint/prevhinticon.res"
#base "../base/filesv3-hint/cancel/main.res"
#base "../base/filesv3-hint/cancel/is_csc.res"
#base "../base/filesv3-hint/cancel/wd25.res"
#base "../base/filesv3-hint/cancel/vis1.res"
#base "../base/filesv3-hint/cancel/pin0.res"

#base "../base/filesv3-hint/cancel-label/main.res"
#base "../base/filesv3-hint/cancel-label/x_pos42.res"
#base "../base/filesv3-hint/cancel-label/ypos151.res"