//	#base "../resource/#beta/c_spacer.res"
	#base "../#customization/scripts/damageindicator.res"
	#base "../#customization/!addons/#enabled/centered_health/hudlayout.res"
	#base "../#customization/!addons/#enabled/jofre_hud/hudlayout.res"
	#base "../#uni_base/filesv1/hudchat/main.res"
	#base "../resource/ui/base/filesv1/huditemeffectmeter/main_fg.res"
	#base "../resource/ui/base/filesv1/huditemeffectmeter/main_main.res"
	#base "../resource/ui/base/filesv1/freezepanel/main.res"
	#base "../resource/ui/base/filesv1/itemattributetracker/main.res"
	#base "../resource/ui/base/filesv1/queuehudstatus/main.res"		
	#base "../resource/ui/base/filesv1/replayreminder/main.res"		
	#base "../resource/ui/base/filesv1/hudupgradepanel/main.res"
	#base "../resource/base/filesv1/hudquickinfo/main.res"							
	#base "../resource/ui/econ/base/questnotifipanel/main.res"
	#base "../resource/ui/econ/base/notifiqueuepanel/main.res"	
	#base "../resource/ui/base/filesv1/cdamage/main.res"
	#base "../resource/ui/base/filesv1/chealth/main.res"
	#base "../#customization/scripts/transparent.res"