#base "../../../base/filesv1/notifipresentpanel/main.res"
#base "../../../base/filesv1/notifipresentpanel/content1.res"
#base "../../../base/filesv1/armory_panel/main.res"
	#base "../../../base/filesv2/footerline/main.res"
	#base "../../../base/filesv2/footerline/xpos0.res"
	#base "../../../base/filesv2/footerline/ypos420.res"
	#base "../../../base/filesv2/footerline/zpos2.res"	