//#base "../resource/#bases/bench_main.res"
#base "base/label1_main.res"
#base "base/label1_autoresize.res"
#base "base/label1_north.res"
#base "base/label1_paintb.res"
#base "base/label1_wrap1.res"
#base "base/divider1.res"
#base "base/button1.res"