#base "../resource/ui/base/filesv1/mapname/main.res"
#base "../resource/ui/base/filesv1/mapname/is-label.res"
#base "../resource/ui/base/filesv1/mapname/vis1.res"
#base "../resource/ui/base/filesv1/mapname/auto-pin.res"
#base "../resource/ui/base/filesv1/mapname/west.res"
#base "../resource/ui/base/filesv1/mapname/dull0.res"
#base "../resource/ui/base/filesv1/mapname/bright0.res"
#base "../resource/base/servername.res"