"Resource/label_vac.res"
{
	"TimeRemainingLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"TimeRemainingLabel"
		"xpos"		"c4703"
		"ypos"		"14"
		"wide"		"260"
		"tall"		"24"
		"autoResize"		"0"
		"pinCorner"		"0"
		"RoundedCorners"		"15"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"tabPosition"		"0"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
	}
}
