#base "../_jofrenew/resource/sourcescheme.res"
#base "../_jofrehud/resource/sourcescheme.res"
#base "../_jofrehud/_tf2exp/sourcescheme.res"
#base "../_jofrehud/_tf2exp/sourceschemebase.res"
//#base "../_tf2hud/resource/sourcescheme.res"
//#base "../_tf2hud/root/resource/sourceschemebase.res"