#base "../base/filesv3-hint/buttonlegend.res"
#base "../disguise_menu/base/hudmenuspydisguise.res"
#base "../base/filesv3-hint/cancel/main.res"
#base "../base/filesv3-hint/cancel/is_label.res"
#base "../base/filesv3-hint/cancel/vis1.res"
#base "../base/filesv3-hint/cancel/pin0.res"
#base "../base/filesv3-hint/teamtoggle.res"

#base "../base/filesv3-hint/cancel-label/main.res"
#base "../base/filesv3-hint/cancel-label/x_pos40.res"
#base "../base/filesv3-hint/cancel-label/ypos129.res"