#base "../base/build-more/mainbg/main.res"
#base "../base/build-more/mainbg/position/wide470.res"
#base "../base/build-more/mainbg/position/xpos0.res"
#base "../base/build-more/mainbg/position/tall170.res"
#base "../base/build-more/mainbg/ctrl_other.res"
#base "../base/build-more/mainbg/image/scale.res"
#base "../base/build-more/mainbg/image/color1.res"
#base "../base/build-more/mainbg/image/content1.res"
// hud_menu_item_bg
#base "../base/v2/divider.res
"
#base "../base/build-more/titlelabel/main.res"
#base "../base/build-more/titlelabel/font/giantbold.res"
#base "../base/build-more/titlelabel/content1.res"
#base "../base/build-more/titlelabel/position/tall38.res"
#base "../base/build-more/titlelabel/text/left.res"

#base "../base/build-more/titlelabelshadow/main.res"
#base "../base/build-more/titlelabelshadow/font/giantbold.res"
#base "../base/build-more/titlelabelshadow/content1.res"
#base "../base/build-more/titlelabelshadow/position/tall38.res"
#base "../base/build-more/titlelabelshadow/text/left.res"

#base "../base/build-more/cancellabel/main.res"
#base "../base/build-more/cancellabel/ctrl/cex.res"
#base "../base/build-more/cancellabel/autopin0.res"
#base "../base/build-more/cancellabel/dullbright.res"
#base "../base/build-more/cancellabel/visenabled1.res"
#base "../base/build-more/cancellabel/position/zpos1.res"
#base "../base/build-more/cancellabel/position/wide200.res"
#base "../base/build-more/cancellabel/position/tall13.res"
#base "../base/build-more/cancellabel/position/ypos49.res"
#base "../base/build-more/cancellabel/font/default.res"
#base "../base/build-more/cancellabel/text/east.res"

#base "../base/class_item/main.res"