#base "../../#uni_base/filesv1/cancelbutton/cancelbutton_main.res"
#base "../../#uni_base/filesv1/cancelbutton/cancelbutton_west.res"
#base "../../#uni_base/filesv1/cancelbutton/cancelbutton_def0.res"
#base "../../#uni_base/filesv1/cancelbutton/cancelbutton_is-button.res"
#base "../../#uni_base/filesv1/cancelbutton/cancelbutton_autoresize_pin.res"
#base "../../#uni_base/filesv1/cancelbutton/cancelbutton_vis1.res"
"servers/InternetGamesPage.res"
{
	"CancelButton"
	{
	//	"ControlName"		"Button"
	//	"fieldName"		"CancelButton"
		"tall"		"24"
	//	"AutoResize"		"0"
	//	"PinCorner"		"0"
	//	"visible"		"1"
	//	"enabled"		"1"
		"tabPosition"		"4"
		"paintbackground"		"1"
		"labelText"		"#ServerBrowser_Cancel"
	//	"textAlignment"		"west"
		"wrap"		"0"
		"Command"		"Close"
	//	"Default"		"0"
	}
}
