	#base	"../../#users/custom/resource/ui/charinfoloadoutsubpanel.res"
	#base	"../../_jofrehud/resource/#beta/menu_reloadbutton.res"
	#base	"../../_stream/resource/ui/charinfoloadoutsubpanel.res"
	#base	"../../_jofrehud/resource/ui/charinfoloadoutsubpanel.res"
	#base	"../../_tf2hud/resource/ui/charinfoloadoutsubpanel.res"