	#base	"../../#users/custom/resource/ui/hudammoweapons.res"
	#base	"../../_jofrehud/_customization/resource/ui/hudammoweapons - style.res"	
	#base	"../../_stream/resource/ui/hudammoweapons.res"
	#base	"../../_jofrehud/resource/ui/hudammoweapons.res"
	#base	"../../_tf2hud/resource/ui/hudammoweapons.res"