	#base	"../../#users/custom/resource/ui/huddamageaccount.res"
	#base 	"../../_jofrehud/_customization/resource/ui/huddamageaccount - style.res"	
	#base	"../../_jofrehud/_customization/resource/ui/dmg_spot.res"
	#base 	"../../_jofrehud/_customization/resource/ui/dmg_value_toggle.res"
	#base 	"../../_jofrehud/_customization/resource/ui/dmg_float.res"
	#base	"../../_stream/resource/ui/huddamageaccount.res"
	#base	"../../_jofrehud/resource/ui/huddamageaccount.res"
	#base	"../../_tf2hud/resource/ui/huddamageaccount.res"