	#base	"../../#users/custom/resource/ui/huditemeffectmeter_halloweensouls.res"
	#base	"../../#users/dane/resource/ui/huditemeffectmeter_halloweensouls.res"
	#base	"../../_stream/resource/ui/huditemeffectmeter_halloweensouls.res"
	#base	"../../_jofrehud/resource/ui/huditemeffectmeter_halloweensouls.res"
	#base	"../../_tf2hud/resource/ui/huditemeffectmeter_halloweensouls.res"