	#base	"../../_custom/resource/ui/huditemattributetracker.res"
	#base	"../../_custom/resource/ui/huditemattributetracker.res"
	#base	"../../_jofrenew/resource/ui/huditemattributetracker.res"
	#base	"../../_jofrehud/resource/ui/huditemattributetracker.res"
	#base	"../../_tf2hud/resource/ui/huditemattributetracker.res"