	#base	"../../#users/custom/resource/ui/hudminigame_collection.res"
	#base	"../../_stream/resource/ui/hudminigame_collection.res"
	#base	"../../_jofrehud/resource/ui/hudminigame_collection.res"
	#base	"../../_jofrehud/_tf2fix/resource/ui/hudminigame_collection.res"	
//	#base	"../../_tf2hud/resource/ui/hudminigame_collection.res"