	#base	"../../#users/custom/resource/ui/matchmakingdashboardeventmatch.res"
	#base	"../../_stream/resource/ui/matchmakingdashboardeventmatch.res"
	#base	"../../_jofrehud/resource/ui/matchmakingdashboardeventmatch.res"
	#base	"../../_jofrehud/_tf2fix/resource/ui/matchmakingdashboardeventmatch.res"
//	#base	"../../_tf2hud/resource/ui/matchmakingdashboardeventmatch.res"