	#base	"../../_stream/resource/ui/spectatortournamentguihealth.res"
	#base	"../../_jofrehud/resource/#beta/hp_player.res"
	#base	"../../_jofrenew/resource/ui/spectatortournamentguihealth.res"
	#base	"../../_jofrehud/resource/ui/spectatortournamentguihealth.res"
	#base	"../../_tf2hud/resource/ui/spectatortournamentguihealth.res"