	#base	"../../#users/custom/resource/ui/spectatorguihealth.res"
	#base 	"../../_jofrehud/resource/#beta/hp_player.res"	
	#base	"../../_stream/resource/ui/spectatorguihealth.res"
	#base	"../../_jofrehud/resource/ui/spectatorguihealth.res"
	#base	"../../_tf2hud/resource/ui/spectatorguihealth.res"